from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Image,
    Table,
    TableStyle,
    HRFlowable,
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.enums import TA_CENTER, TA_LEFT, TA_RIGHT
from reportlab.lib import colors
from reportlab.lib.units import cm
from reportlab.lib.pagesizes import A4
 
 
# ─── Brand Colors ────────────────────────────────────────────────────────────
NAVY       = colors.HexColor("#0D1B2A")   # header / section titles
BLUE       = colors.HexColor("#1B63A8")   # accent / sub-headings
LIGHT_BLUE = colors.HexColor("#E8F1FB")   # row alternating / highlight bg
GOLD       = colors.HexColor("#F5A623")   # KPI accent bar
GRAY_TEXT  = colors.HexColor("#4A4A4A")   # body text
GRAY_LINE  = colors.HexColor("#D0D7E2")   # dividers
WHITE      = colors.white
 
 
# ─── Page callbacks (header / footer on every page) ──────────────────────────
def _on_first_page(canvas, doc):
    _draw_header(canvas, doc)
    _draw_footer(canvas, doc)
 
 
def _on_later_pages(canvas, doc):
    _draw_header(canvas, doc)
    _draw_footer(canvas, doc)
 
 
def _draw_header(canvas, doc):
    """Dark navy banner across the top."""
    w, h = A4
    banner_h = 2.2 * cm
 
    canvas.saveState()
    # Navy band
    canvas.setFillColor(NAVY)
    canvas.rect(0, h - banner_h, w, banner_h, fill=1, stroke=0)
 
    # Gold accent stripe
    canvas.setFillColor(GOLD)
    canvas.rect(0, h - banner_h - 4, w, 4, fill=1, stroke=0)
 
    # Company / report title inside banner
    canvas.setFillColor(WHITE)
    canvas.setFont("Helvetica-Bold", 14)
    canvas.drawString(doc.leftMargin, h - banner_h + 0.75 * cm,
                      "BUSINESS DATA ANALYSIS REPORT")
 
    canvas.setFont("Helvetica", 9)
    canvas.setFillColor(colors.HexColor("#A8C4E0"))
    canvas.drawRightString(w - doc.rightMargin, h - banner_h + 0.75 * cm,
                           "Confidential · Internal Use Only")
    canvas.restoreState()
 
 
def _draw_footer(canvas, doc):
    """Light footer with page number."""
    w, _ = A4
    canvas.saveState()
    canvas.setStrokeColor(GRAY_LINE)
    canvas.setLineWidth(0.5)
    canvas.line(doc.leftMargin, 1.4 * cm, w - doc.rightMargin, 1.4 * cm)
 
    canvas.setFont("Helvetica", 8)
    canvas.setFillColor(GRAY_TEXT)
    canvas.drawString(doc.leftMargin, 0.9 * cm,
                      "Generated by Business Analytics Suite")
    canvas.drawRightString(w - doc.rightMargin, 0.9 * cm,
                           f"Page {doc.page}")
    canvas.restoreState()
 
 
# ─── Style factory ───────────────────────────────────────────────────────────
def _build_styles():
    base = getSampleStyleSheet()
 
    styles = {}
 
    styles["section_title"] = ParagraphStyle(
        "section_title",
        fontName="Helvetica-Bold",
        fontSize=11,
        textColor=WHITE,
        leading=16,
        spaceAfter=0,
        spaceBefore=0,
        leftIndent=8,
    )
 
    styles["kpi_label"] = ParagraphStyle(
        "kpi_label",
        fontName="Helvetica",
        fontSize=9,
        textColor=GRAY_TEXT,
        leading=13,
    )
 
    styles["kpi_value"] = ParagraphStyle(
        "kpi_value",
        fontName="Helvetica-Bold",
        fontSize=16,
        textColor=NAVY,
        leading=20,
    )
 
    styles["body"] = ParagraphStyle(
        "body",
        fontName="Helvetica",
        fontSize=9.5,
        textColor=GRAY_TEXT,
        leading=14,
        spaceAfter=4,
    )
 
    styles["insight_bullet"] = ParagraphStyle(
        "insight_bullet",
        fontName="Helvetica",
        fontSize=9.5,
        textColor=GRAY_TEXT,
        leading=14,
        leftIndent=12,
        spaceAfter=5,
    )
 
    styles["chart_caption"] = ParagraphStyle(
        "chart_caption",
        fontName="Helvetica-Oblique",
        fontSize=8.5,
        textColor=GRAY_TEXT,
        alignment=TA_CENTER,
        spaceBefore=4,
    )
 
    return styles
 
 
# ─── Helper: coloured section header band ────────────────────────────────────
def _section_header(title, styles):
    """Returns a 1-cell Table that acts as a coloured section banner."""
    cell = Paragraph(title.upper(), styles["section_title"])
    tbl = Table([[cell]], colWidths=["100%"])
    tbl.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BLUE),
        ("TOPPADDING",    (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("LEFTPADDING",   (0, 0), (-1, -1), 8),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 8),
        ("ROUNDEDCORNERS", [4]),
    ]))
    return tbl
 
 
# ─── Helper: KPI cards row ───────────────────────────────────────────────────
def _kpi_table(kpis, styles):
    """
    kpis: list of (label, value_str) tuples.
    Renders them side-by-side in a light card layout.
    """
    cells = []
    for label, value in kpis:
        block = [
            Paragraph(label, styles["kpi_label"]),
            Paragraph(value,  styles["kpi_value"]),
        ]
        cells.append(block)
 
    col_w = [A4[0] / len(kpis) - 1 * cm] * len(kpis)   # equal columns
    tbl = Table([cells], colWidths=col_w, rowHeights=None)
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0, 0), (-1, -1), LIGHT_BLUE),
        ("TOPPADDING",    (0, 0), (-1, -1), 10),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 10),
        ("LEFTPADDING",   (0, 0), (-1, -1), 14),
        ("RIGHTPADDING",  (0, 0), (-1, -1), 14),
        ("VALIGN",        (0, 0), (-1, -1), "MIDDLE"),
        ("LINEAFTER",     (0, 0), (-2, -1), 1, GRAY_LINE),
        ("ROUNDEDCORNERS", [4]),
    ]))
    return tbl
 
 
# ─── Main function ────────────────────────────────────────────────────────────
def generate_pdf(report, insights, total_sales, total_profit):
    doc = SimpleDocTemplate(
        "report.pdf",
        pagesize=A4,
        topMargin=3.2 * cm,   # leave room for header banner
        bottomMargin=2.0 * cm,
        leftMargin=1.8 * cm,
        rightMargin=1.8 * cm,
    )
 
    styles = _build_styles()
    elements = []
 
    # ── Intro spacer (banner already drawn by callback) ──────────────────────
    elements.append(Spacer(1, 0.5 * cm))
 
    # ── GENERAL INFORMATION ───────────────────────────────────────────────────
    elements.append(_section_header("General Information", styles))
    elements.append(Spacer(1, 0.3 * cm))
 
    info_data = [
        [Paragraph("<b>Rows</b>",    styles["body"]),
         Paragraph(str(report["rows"]),    styles["body"])],
        [Paragraph("<b>Columns</b>", styles["body"]),
         Paragraph(str(report["columns"]), styles["body"])],
    ]
    info_tbl = Table(info_data, colWidths=[4 * cm, None])
    info_tbl.setStyle(TableStyle([
        ("ROWBACKGROUNDS",  (0, 0), (-1, -1), [WHITE, LIGHT_BLUE]),
        ("TOPPADDING",      (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING",   (0, 0), (-1, -1), 6),
        ("LEFTPADDING",     (0, 0), (-1, -1), 10),
        ("RIGHTPADDING",    (0, 0), (-1, -1), 10),
        ("GRID",            (0, 0), (-1, -1), 0.4, GRAY_LINE),
    ]))
    elements.append(info_tbl)
    elements.append(Spacer(1, 0.6 * cm))
 
    # ── BUSINESS STATISTICS (KPI cards) ──────────────────────────────────────
    elements.append(_section_header("Business Statistics", styles))
    elements.append(Spacer(1, 0.3 * cm))
 
    kpis = []
    if total_sales is not None:
        kpis.append(("Total Sales", f"{total_sales:,.2f}"))
    if total_profit is not None:
        kpis.append(("Total Profit", f"{total_profit:,.2f}"))
 
    if kpis:
        elements.append(_kpi_table(kpis, styles))
 
    elements.append(Spacer(1, 0.6 * cm))
 
    # ── KEY INSIGHTS ──────────────────────────────────────────────────────────
    elements.append(_section_header("Key Insights", styles))
    elements.append(Spacer(1, 0.3 * cm))
 
    for i, insight in enumerate(insights):
        bg = LIGHT_BLUE if i % 2 == 0 else WHITE
        row = [[Paragraph(f"&#8250;  {insight}", styles["insight_bullet"])]]
        tbl = Table(row, colWidths=["100%"])
        tbl.setStyle(TableStyle([
            ("BACKGROUND",    (0, 0), (-1, -1), bg),
            ("TOPPADDING",    (0, 0), (-1, -1), 5),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
            ("LEFTPADDING",   (0, 0), (-1, -1), 10),
            ("RIGHTPADDING",  (0, 0), (-1, -1), 10),
            ("LINEBELOW",     (0, 0), (-1, -1), 0.3, GRAY_LINE),
        ]))
        elements.append(tbl)
 
    elements.append(Spacer(1, 0.6 * cm))
 
    # ── MISSING VALUES CHART ──────────────────────────────────────────────────
    try:
        elements.append(_section_header("Missing Values Analysis", styles))
        elements.append(Spacer(1, 0.4 * cm))
        img = Image("missing_values.png", width=14 * cm, height=8.5 * cm)
        img.hAlign = "CENTER"
        elements.append(img)
        elements.append(
            Paragraph("Figure 1 — Distribution of missing values per column",
                       styles["chart_caption"])
        )
        elements.append(Spacer(1, 0.6 * cm))
    except Exception:
        pass
 
    # ── PROFIT BY CATEGORY CHART ──────────────────────────────────────────────
    try:
        elements.append(_section_header("Profit by Category", styles))
        elements.append(Spacer(1, 0.4 * cm))
        img = Image("profit_by_category.png", width=14 * cm, height=8.5 * cm)
        img.hAlign = "CENTER"
        elements.append(img)
        elements.append(
            Paragraph("Figure 2 — Total profit broken down by product category",
                       styles["chart_caption"])
        )
        elements.append(Spacer(1, 0.4 * cm))
    except Exception:
        pass
 
    # ── BUILD ─────────────────────────────────────────────────────────────────
    doc.build(
        elements,
        onFirstPage=_on_first_page,
        onLaterPages=_on_later_pages,
    )